### ISSUE TITLE
логи не хранят в git

### ISSUE THREAD

**Issue by a-f-larionov** [nicks219/Random-Song-Search-Engine#11]
удалить Logger.txt из репозитория
добавить его в .gitignore

Если нужно жесткое хранение логов - для этого исопльзуют или файлы или бд

это динамические данные, такие же как товары, так что в git-е такое не хранят

**Comment by nicks219** [comment]
Где он в репе, не вижу?

**Comment by a-f-larionov** [comment]
На нашел. Возможно перепутал с другим репозиторием. Закрываем.
