### ISSUE TITLE
README.md not found

### ISSUE THREAD

**Issue by a-f-larionov** [nicks219/Random-Song-Search-Engine#2]
Exception README.md file was found.

See this file: https://github.com/a-f-larionov/RazorPagesWebApplication/blob/master/README.md

**Comment by a-f-larionov** [comment]
What is news?

**Comment by a-f-larionov** [comment]
Нужны ссылка на коммит и описание изменений, открой задачу, поставь Assigned на меня(пока я сам не могу этого сделать)

**Comment by nicks219** [comment]
создан readme.md файл
https://github.com/nicks219/Random-Song-Search-Engine/commit/a18f1985dcba6aa9e0440ea7d574a7455d1092c6

**Comment by a-f-larionov** [comment]
Проверил, всё отлично! закрываем!
