### ISSUE TITLE
RazorDbContext переименовать в DBContext

### ISSUE THREAD

**Issue by a-f-larionov** [nicks219/Random-Song-Search-Engine#7]
RazorDbContext похоже в слове Razor нет необходимости.
А т.к. в C# DBContext является обычным делом, то пусть так и зовется

**Comment by nicks219** [comment]
Класс DbContext уже есть в EntityFrameworkCore, поддерживаю оставить имя RazorDbContext

**Comment by a-f-larionov** [comment]
Класс RazorDBContext имеет имеет отношение к [DB Context](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext?view=entity-framework-6.2.0)

а какое отношение он имеет к [Razor](https://www.w3schools.com/asp/razor_intro.asp) ?

**Comment by nicks219** [comment]
На данный момент у меня не хватает опыта, чтобы придумать лучшее название. 
Я переименовывал, получался менее читаемый код. 
Подскажи корректный вариант.

**Comment by a-f-larionov** [comment]
DBContext чем плохо?

**Comment by a-f-larionov** [comment]
Открой задачу заново?

**Comment by nicks219** [comment]
Переименование RazorDbContext в DbContext вызвало конфликт имен по всему приложению, вернуть код обратно заняло время - т.к. сложно было отделить "бывший RazorDbContext" от EntityFrameworkCore класса DbContext. Поэтому, вернув всё обратно, я закрыл задачу.

**Comment by nicks219** [comment]
Переименование RazorDbContext в DatabaseContext. 
https://github.com/nicks219/Random-Song-Search-Engine/commit/6d4495904e18c02e79ac92fb0cbb3e82cb14a2bb

**Comment by a-f-larionov** [comment]
Проверил, закрываем.
